import  customtkinter
customtkinter.set_default_color_theme("../theme/theme.json")
app = customtkinter.CTk()
screen_width = app.winfo_screenwidth()
screen_height = app.winfo_screenheight()
app.geometry(f"{screen_width}x{screen_height}+0+0")
app.title('KeepControl')
#formulaire de connexion
frameForm = customtkinter.CTkFrame(app, width=900, height=350)
frameForm.pack(expand=True)
formTitre = customtkinter.CTkLabel(frameForm,text="Compte Personnel", font=("Lota Grotesque", 40))
formTitre.place(x=20, y=20)
formNom = customtkinter.CTkLabel(frameForm,text="Nom utilisateur :", )
formNom.place(x=20, y=120)
champNom = customtkinter.CTkEntry(frameForm, width=350, height=30)
champNom.place(x=180,y=120)
formMdp = customtkinter.CTkLabel(frameForm,text="Mot de passe :")
formMdp.place(x=20, y=200)
champMdp = customtkinter.CTkEntry(frameForm, width=350, height=30)
champMdp.place(x=180,y=200)
formConf = customtkinter.CTkLabel(frameForm,text="Confirmez mot de passe :")
formConf.place(x=20, y=280)
champConf = customtkinter.CTkEntry(frameForm, width=350, height=30)
champConf.place(x=280,y=280)
#boutonsuivant
suiv = customtkinter.CTkButton(app, text="Suivant", text_color="white", width=50, height=40,fg_color="#6c757d", state="disabled")
suiv.place(x=1010,y=550)
#Progression
framePro = customtkinter.CTkFrame(app, width=1250, height=58, fg_color="white")
framePro.pack(side="bottom")
#etape
barreCompte = customtkinter.CTkFrame(framePro, width=450, height=10, fg_color="#212529",corner_radius=0)
barreCompte.place(x=0,y=0)
etapeCompte=customtkinter.CTkLabel(framePro, text="Création de compte",)
etapeCompte.cget("font").configure(size=25)
etapeCompte.place(x=100, y=15)
barreConf = customtkinter.CTkFrame(framePro, width=450, height=10, fg_color="#212529",corner_radius=0)
barreConf.place(x=450,y=0)
etapeConf=customtkinter.CTkLabel(framePro, text="Configuration de la maison",)
etapeConf.cget("font").configure(size=25)
etapeConf.place(x=520, y=15)
barreFin = customtkinter.CTkFrame(framePro, width=450, height=10, fg_color="#212529",corner_radius=0)
barreFin.place(x=900,y=0)
etapeFin=customtkinter.CTkLabel(framePro, text="Terminé")
etapeFin.cget("font").configure(size=25)
etapeFin.place(x=1050, y=15)
app.mainloop()